"""Review cost recording hook for Kiro reviewer workflow.

This module provides the interface for recording cloud tokens consumed
when Kiro reviews code generated by the local model. It can be called
programmatically or from the command line.

Usage (CLI):
    python -m local_coder.review_hook --session-id <id> --tokens <count> [--db-path <path>]

Usage (Python):
    from local_coder.review_hook import record_review
    record_review(session_id="abc123", tokens=1500)
"""

import argparse
import sys
from pathlib import Path

from local_coder.token_tracker import SessionTracker, SessionNotFoundError, InvalidReviewCostError

DEFAULT_DB_PATH = Path(".codesearch") / "index.db"


def record_review(
    session_id: str,
    tokens: int,
    db_path: Path | None = None,
) -> None:
    """Record cloud tokens consumed by Kiro reviewing generated code.

    Args:
        session_id: The session ID from the generation that triggered review.
        tokens: Number of cloud tokens consumed by the review.
        db_path: Path to the SQLite database. Defaults to .codesearch/index.db.

    Raises:
        SessionNotFoundError: If the session_id doesn't exist.
        InvalidReviewCostError: If tokens is out of range [1, 10_000_000].
    """
    if db_path is None:
        db_path = DEFAULT_DB_PATH

    tracker = SessionTracker(db_path)
    tracker.record_review_cost(session_id, tokens)


def main() -> None:
    """CLI entry point for recording review costs."""
    parser = argparse.ArgumentParser(
        description="Record Kiro review token costs for a generation session"
    )
    parser.add_argument("--session-id", required=True,
                        help="Session ID from the generation that was reviewed")
    parser.add_argument("--tokens", type=int, required=True,
                        help="Number of cloud tokens consumed by the review")
    parser.add_argument("--db-path", type=Path, default=None,
                        help=f"Path to SQLite database (default: {DEFAULT_DB_PATH})")

    args = parser.parse_args()

    try:
        record_review(args.session_id, args.tokens, args.db_path)
        print(f"Recorded {args.tokens:,} review tokens for session {args.session_id}")
    except SessionNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except InvalidReviewCostError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
